FROM ubuntu:latest


# Comando fixo que sempre será executado, independente dos valores passados no docker run
ENTRYPOINT [ "echo", "Hello" ]

# Comando que pode ser substituído pelo valor passado no docker run
CMD ["World"]